import "./globals.css";
import Header from "./components/header/Header";

import { Space_Grotesk } from "next/font/google";
import Footer from "./components/footer/Footer";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="lt" className={spaceGrotesk.className}>
      <body className="bg-black">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
